name: challenge
on: [push]

jobs:
  job1:
    name: Job One
    runs-on: ubuntu-latest
    steps:
      - name: Step One
      - run: date
  job2:
    name: Job Two
    runs-on: windows-latest
    steps:
      - name: Step One
      - run: "Get-Date"
  job3:
    name: Job Three
    runs-on: macos-latest
    steps:
      - name: Step One
      - run: date
  job4:
    name: Job Four
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps: 
     - name: Step One
     - run: date 

